name: "build"

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

jobs:
  build-wasm-module:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Build wasm module"
        shell: bash
        run: make build-wasm-plugin extract-wasm-plugin

      - name: "Cache generated .wasm file"  
        uses: actions/cache@v2
        with:
          path: |
            bin/
          key: wasm-module-build # -${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build-wasm-module
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        # no need of recursion, .wasm file is already built and cached

      - name: "Install func-e"
        shell: bash
        run: curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin
      
      - name: "Restore the wasm files cache"
        uses: actions/cache@v2
        with:
          path: |
            bin/
          key: wasm-module-build # -${{ github.sha }}

      - name: "Spin up server and envoy"
        shell: bash
        run: |
          docker run --rm -d -p 8000:10080 jcchavezs/httpmole -response-status=200 &
          func-e run -c envoy-config.yaml --log-level info --component-log-level wasm:debug &

      - name: "Run tests"
        shell: bash
        run: |
          ./tests.sh