name: test
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  build-wasm-module:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Retriving modsecurity-wasm-filter hash"
        # Cache's key based on the modesecurity-wasm-filter repo, it should lead to
        # rebuild the wasm module only if there are updates on that repo.
        run: echo "CACHE_MODSEC_WASM_FILTER_HASH=${{ hashFiles('modsecurity-wasm-filter/**') }}" >> $GITHUB_ENV
        
      - name: "Attempts to restore cache"
        id: cache-wasm-bin
        uses: actions/cache@v3
        with:
          path: |
            bin/
          key: wasm-module-build-${{ env.CACHE_MODSEC_WASM_FILTER_HASH }}

      - name: "Build wasm module"
        if: steps.cache-wasm-bin.outputs.cache-hit != 'true'
        shell: bash
        run: make build-wasm-plugin extract-wasm-plugin

      - name: "Cache generated .wasm file"  
        if: steps.cache-wasm-bin.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: |
            bin/
          key: wasm-module-build-${{ env.CACHE_MODSEC_WASM_FILTER_HASH }}

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-wasm-module
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Install func-e"
        shell: bash
        run: curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin
      
      - name: "Restore the wasm files cache"
        uses: actions/cache@v3
        with:
          path: |
            bin/
          key: wasm-module-build-${{ hashFiles('modsecurity-wasm-filter/**') }}

      - name: "Spin up server and envoy"
        shell: bash
        run: |
          docker run --rm -d -p 8000:10080 jcchavezs/httpmole -response-status=200 &
          func-e run -c envoy-config.yaml --log-level info --component-log-level wasm:debug &

      - name: "Run tests"
        shell: bash
        run: |
          ./tests.sh